
name: Deploy Node.js to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Enhanced OS detection
          if [ -f /etc/os-release ]; then
            . /etc/os-release
            OS_TYPE=$ID
          elif [ -f /etc/redhat-release ]; then
            OS_TYPE="rhel"
          elif [ -f /etc/amazon-release ]; then
            OS_TYPE="amzn"
          else
            echo "Unable to detect OS, assuming Amazon Linux"
            OS_TYPE="amzn"
          fi
          
          echo "Detected OS: $OS_TYPE"
          
          # Install dependencies if they don't exist
          if ! command -v git &> /dev/null; then
            echo "Installing Git..."
            if [[ "$OS_TYPE" == "amzn" || "$OS_TYPE" == "rhel" || "$OS_TYPE" == "centos" ]]; then
              # Amazon Linux, RHEL, CentOS
              sudo yum update -y
              sudo yum install git -y
            elif [[ "$OS_TYPE" == "ubuntu" || "$OS_TYPE" == "debian" ]]; then
              # Ubuntu, Debian
              sudo apt update -y
              sudo apt install git -y
            else
              echo "Unrecognized OS. Trying yum..."
              sudo yum update -y
              sudo yum install git -y || (echo "yum failed, trying apt..." && sudo apt update -y && sudo apt install git -y)
            fi
          fi
          
          if ! command -v node &> /dev/null; then
            echo "Installing Node.js 20.x..."
            if [[ "$OS_TYPE" == "amzn" || "$OS_TYPE" == "rhel" || "$OS_TYPE" == "centos" ]]; then
              # Amazon Linux, RHEL, CentOS
              curl -sL https://rpm.nodesource.com/setup_20.x.x | sudo bash -
              sudo yum install -y nodejs
            elif [[ "$OS_TYPE" == "ubuntu" || "$OS_TYPE" == "debian" ]]; then
              # Ubuntu, Debian
              curl -sL https://deb.nodesource.com/setup_20.x.x | sudo -E bash -
              sudo apt install -y nodejs
            else
              echo "Unrecognized OS. Trying yum for Node.js installation..."
              curl -sL https://rpm.nodesource.com/setup_20.x.x | sudo bash -
              sudo yum install -y nodejs || (echo "yum failed, trying apt..." && curl -sL https://deb.nodesource.com/setup_20.x.x | sudo -E bash - && sudo apt install -y nodejs)
            fi
          fi
          
          # Print versions for verification
          git --version
          node --version
          npm --version
          
          # Ensure deployment directory exists
          mkdir -p /home/
          cd /home/
          
          # Clone or pull repository
          if [ -d ".git" ]; then
            git pull
          else
            git clone ${{ github.repository }} .
          fi
          
          # Install dependencies and build
          npm ci
          npm run build --if-present
          
          # Start or restart the application
          npm run start
